services:
  - type: web
    name: ticketmaster-events-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TICKETMASTER_API_KEY
        sync: false  # Set this in Render dashboard
      - key: PORT
        value: 8000
    autoDeploy: true